name: Sync to Hugging Face Spaces

on: [push] # Dispara em qualquer push para testarmos

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # ⚠️ Lembre de trocar 'seu-usuario' e 'nome-do-seu-space' pelos seus links reais do Hugging Face!
        run: git push --force https://seu-usuario:$HF_TOKEN@huggingface.co/spaces/seu-usuario/nome-do-seu-space main
